  server:
    port: 8080
    session-timeout: 30
    tomcat.max-threads: 0
    tomcat.uri-encoding: UTF-8

  spring:
    datasource:
      url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
      username: root
      password: root
    mvc:
      view:
        prefix: /WEB-INF/
        suffix: .jsp
      static-path-pattern: /static/**

  mybatis:
    type-aliases-package: com.example.model
    mapper-locations: classpath:mapper/*.xml